services:
  build:
    image: ghcr.io/gohugoio/hugo
    command: --gc --minify
    user: ":"
    volumes:
      - ".:/project"
  server:
    image: ghcr.io/gohugoio/hugo
    command: server --bind 0.0.0.0
    user: ":"
    volumes:
      - ".:/project"
      - "hugo_cache:/cache" # persistent cache volume
    ports:
      - "1313:1313"

volumes:
  hugo_cache:
